---
# Source: ingressmonitorcontroller/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ingressmonitorcontroller
  annotations:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.102"
    release: "ingressmonitorcontroller"
    heritage: "Tiller"
    version: v1.0.102
    
    group: com.stakater.platform
    provider: stakater
    
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://google.com
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
    # how often (in seconds) monitors should be synced to their Kubernetes resources (0 = disabled)
    resyncPeriod: 0
    # creationDelay is a duration string to add a delay before creating new monitor (e.g., to allow DNS to catch up first)
    # https://golang.org/pkg/time/#ParseDuration
    creationDelay: 0
  

