---
# Source: ingressmonitorcontroller/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.85"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.85
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
