apiVersion: v2
name: ingressmonitorcontroller
description: IngressMonitorController Operator chart that runs on kubernetes

# Helm chart Version
version: 2.1.29

# Application version to be deployed
appVersion: 2.1.29

keywords:
  - IngressMonitorController
  - IngressMonitorController Operator
  - kubernetes
  - Ingress
  - Route
home: https://github.com/stakater/IngressMonitorController
icon: https://raw.githubusercontent.com/stakater/IngressMonitorController/master/assets/web/IMC-round-100px.png
sources:
  - https://github.com/stakater/IngressMonitorController
