apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ingress-monitor-controller
  labels:
    app: ingress-monitor-controller
    provider: stakater
    version: 1.0.0
  name: ingress-monitor-controller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: ingress-monitor-controller
      labels:
        app: ingress-monitor-controller
        provider: stakater
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_FILE_PATH
          value: /etc/ingress-monitor-controller/config.yaml
# TODO: Update name
        image: stakater/ingress-monitor-controller:implementation
        imagePullPolicy: Always
#       livenessProbe:
#          exec:
#            command:
#            - cat
#            - /tmp/restarteveryday
#          initialDelaySeconds: 86164
        name: ingress-monitor-controller
        volumeMounts:
        - mountPath: /etc/ingress-monitor-controller
          name: config-volume
#      serviceAccountName: ingress-monitor-controller-svcaccount
      volumes:
      - configMap:
          name: ingress-monitor-controller
        name: config-volume