kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingressmonitorcontroller
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
roleRef:
  kind: Role
  name: ingressmonitorcontroller
  apiGroup: rbac.authorization.k8s.io
