apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
{{- if .Values.ingressMonitorController.deployment.annotations }}
{{ toYaml .Values.ingressMonitorController.deployment.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "ingressmonitorcontroller.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.ingressMonitorController.deployment.labels }}
{{ toYaml .Values.ingressMonitorController.deployment.labels | indent 4 }}
{{- end }}
{{- if .Values.ingressMonitorController.matchLabels }}
{{ toYaml .Values.ingressMonitorController.matchLabels | indent 4 }}
{{- end }}
{{- if .Values.ingressMonitorController.useFullName }}
  name: {{ template "ingressmonitorcontroller.fullname" . }}
{{- else }}
  name: {{ template "ingressmonitorcontroller.name" . }}
{{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "ingressmonitorcontroller.name" . }}
      release: {{ .Release.Name | quote }}
{{- if .Values.ingressMonitorController.matchLabels }}
{{ toYaml .Values.ingressMonitorController.matchLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "ingressmonitorcontroller.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
{{- if .Values.ingressMonitorController.deployment.labels }}
{{ toYaml .Values.ingressMonitorController.deployment.labels | indent 8 }}
{{- end }}
{{- if .Values.ingressMonitorController.matchLabels }}
{{ toYaml .Values.ingressMonitorController.matchLabels | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.ingressMonitorController.tolerations }}
      tolerations:
{{ toYaml .Values.ingressMonitorController.tolerations | indent 8 }}
      {{- end }}
      containers:
      - env:
      {{- range .Values.ingressMonitorController.secrets }}
        - name: {{ .variable }}
          valueFrom:
            secretKeyRef:
              name: {{ .name }}
              key: {{ .key }}
      {{- end }}
      {{- if .Values.ingressMonitorController.watchNamespace }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Values.ingressMonitorController.watchNamespace | quote }}
      {{- end }}
        - name: CONFIG_FILE_PATH
          value: {{ .Values.ingressMonitorController.configFilePath }}
        - name: LOG_LEVEL
          value: {{ .Values.ingressMonitorController.logLevel }}
        - name: LOG_FORMAT
          value: {{ .Values.ingressMonitorController.logFormat }}
        image: "{{ .Values.ingressMonitorController.image.name }}:{{ .Values.ingressMonitorController.image.tag }}"
        imagePullPolicy: {{ .Values.ingressMonitorController.image.pullPolicy }}
      {{- if .Values.ingressMonitorController.useFullName }}
        name: {{ template "ingressmonitorcontroller.fullname" . }}
      {{- else }}
        name: {{ template "ingressmonitorcontroller.name" . }}
      {{- end }}
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
      {{- if .Values.ingressMonitorController.useFullName }}
          name: {{ template "ingressmonitorcontroller.fullname" . }}-vol
      {{- else }}
          name: {{ template "ingressmonitorcontroller.name" . }}-vol
      {{- end }}
      serviceAccountName: {{ template "ingressmonitorcontroller.serviceAccountName" . }}
      volumes:
      {{- if .Values.ingressMonitorController.useFullName }}
        - name: {{ template "ingressmonitorcontroller.fullname" . }}-vol
      {{- else }}
        - name: {{ template "ingressmonitorcontroller.name" . }}-vol
      {{- end }}
      {{- if eq .Values.ingressMonitorController.mount "secret" }}
          secret:
          {{- if .Values.ingressMonitorController.useFullName }}
            secretName: {{ template "ingressmonitorcontroller.fullname" . }}
          {{- else }}
            secretName: {{ template "ingressmonitorcontroller.name" . }}
          {{- end }}
      {{ else }}
          configMap:
          {{- if .Values.ingressMonitorController.useFullName }}
            name: {{ template "ingressmonitorcontroller.fullname" . }}
          {{- else }}
            name: {{ template "ingressmonitorcontroller.name" . }}
          {{- end }}
      {{- end }}