---
# Source: IngressMonitorController/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  labels:
    app: ingressmonitorcontroller
    version: 1.0.10
    group: com.stakater.platform
    provider: stakater
    chart: "IngressMonitorController-1.0.10"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://google.com
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
