---
# Source: ingressmonitorcontroller/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: ingressmonitorcontroller
  labels:
    app: ingressmonitorcontroller
    version: 1.0.15
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.15"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ingressmonitorcontroller
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      annotations:
        configmap.fabric8.io/update-on-change: ingressmonitorcontroller
      labels:
        app: ingressmonitorcontroller
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          value: "tools"
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        image: "stakater/ingressmonitorcontroller:1.0.15"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: config-volume
      serviceAccountName: ingressmonitorcontroller
      volumes:
      - configMap:
          name: ingressmonitorcontroller
        name: config-volume
