---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: endpointmonitors.endpointmonitor.stakater.com
spec:
  group: endpointmonitor.stakater.com
  names:
    kind: EndpointMonitor
    listKind: EndpointMonitorList
    plural: endpointmonitors
    singular: endpointmonitor
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: EndpointMonitor is the Schema for the endpointmonitors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EndpointMonitorSpec defines the desired state of EndpointMonitor
            properties:
              appInsightsConfig:
                description: Configuration for AppInsights Monitor Provider
                properties:
                  frequency:
                    description: 'Sets how often the test should run from each test
                      location. Possible values: `300,600,900` seconds'
                    type: integer
                  retryEnable:
                    description: 'If its `true`, falied test will be retry after a
                      short interval. Possible values: `true, false`'
                    type: boolean
                  statusCode:
                    description: Returned status code that is counted as a success
                    type: integer
                type: object
              forceHttps:
                description: Force monitor endpoint to use HTTPS
                type: boolean
              gcloudConfig:
                description: Configuration for Google Cloud Monitor Provider
                properties:
                  projectId:
                    description: Google Cloud Project ID
                    type: string
                type: object
              healthEndpoint:
                type: string
              pingdomConfig:
                description: Configuration for Pingdom Monitor Provider
                properties:
                  alertContacts:
                    description: '`-` separated contact id''s (e.g. "1234567_8_9-9876543_2_1")'
                    type: string
                  alertIntegrations:
                    description: '`-` separated set list of integrations ids (e.g.
                      "91166-12168")'
                    type: string
                  basicAuthUser:
                    description: Required for basic-authentication
                    type: string
                  notifyWhenBackUp:
                    description: Set to "false" to disable recovery notifications
                    type: boolean
                  paused:
                    description: Set to "true" to pause checks
                    type: boolean
                  requestHeaders:
                    description: Custom pingdom request headers
                    type: string
                  resolution:
                    description: The pingdom check interval in minutes
                    type: integer
                  sendNotificationWhenDown:
                    description: How many failed check attempts before notifying
                    type: integer
                  shouldContain:
                    description: Set to text string that has to be present in the
                      HTML code of the page
                    type: string
                  sslDownDaysBefore:
                    description: Consider down prior to certificate expiring Select
                      the number of days prior to your certificate expiry date that
                      you want to consider the check down. At this day your check
                      will be considered down and if applicable a down alert will
                      be sent.
                    type: integer
                  tags:
                    description: Comma separated set of tags to apply to check (e.g.
                      "testing,aws")
                    type: string
                  teamAlertContacts:
                    description: '`-` separated team id''s (e.g. "1234567_8_9-9876543_2_1")'
                    type: string
                  verifyCertificate:
                    description: Monitor SSL/TLS certificate Monitor the validity
                      of your SSL/TLS certificate. With this enabled Uptime checks
                      will be considered DOWN when the certificate becomes invalid
                      or expires. SSL/TLS certificate monitoring is available for
                      HTTP checks.
                    type: boolean
                type: object
              providers:
                description: Comma separated list of providers
                type: string
              statusCakeConfig:
                description: Configuration for StatusCake Monitor Provider
                properties:
                  basicAuthUser:
                    description: Basic Auth User
                    type: string
                  checkRate:
                    description: Set Check Rate for the monitor
                    type: integer
                  confirmation:
                    description: Confirmation value ranges from (0,10)
                    maximum: 10
                    minimum: 0
                    type: integer
                  contactGroup:
                    description: Contact Group to be alerted.
                    type: string
                  enableSslAlert:
                    description: Enable SSL Alert
                    type: boolean
                  findString:
                    description: String to look for within the response. Considered
                      down if not found
                    type: string
                  followRedirect:
                    description: Enable ingress redirects
                    type: boolean
                  nodeLocations:
                    description: Comma separated list of Node Location IDs
                    type: string
                  paused:
                    description: Pause the service
                    type: boolean
                  pingUrl:
                    description: Webhook for alerts
                    type: string
                  port:
                    description: TCP Port
                    type: integer
                  realBrowser:
                    description: Enable Real Browser
                    type: boolean
                  statusCodes:
                    description: Comma separated list of HTTP codes to trigger error
                      on
                    type: string
                  testTags:
                    description: Comma separated list of tags
                    type: string
                  testType:
                    description: Set Test type - HTTP, TCP, PING
                    type: string
                  triggerRate:
                    description: Minutes to wait before sending an alert
                    type: integer
                type: object
              updownConfig:
                description: Configuration for Updown Monitor Provider
                properties:
                  enable:
                    description: Enable or disable checks
                    type: boolean
                  period:
                    description: The pingdom check interval in seconds
                    type: integer
                  publishPage:
                    description: Make status page public or not
                    type: boolean
                  requestHeaders:
                    description: Additional request headers for API calls
                    type: string
                type: object
              uptimeConfig:
                description: Configuration for Uptime Monitor Provider
                properties:
                  checkType:
                    description: The uptime check type that can be HTTP/DNS/ICMP etc.
                    type: string
                  contacts:
                    description: Add one or more contact groups separated by `,`
                    type: string
                  interval:
                    description: The uptime check interval in seconds
                    type: integer
                  locations:
                    description: Add different locations for the check
                    type: string
                  tags:
                    description: Add one or more tags for the check separated by `,`
                    type: string
                type: object
              uptimeRobotConfig:
                description: Configuration for UptimeRobot Monitor Provider
                properties:
                  alertContacts:
                    description: The uptimerobot alertContacts to be associated with
                      this monitor
                    type: string
                  customHTTPStatuses:
                    description: 'Defines which http status codes are treated as up
                      or down For ex: 200:0_401:1_503:1 (to accept 200 as down and
                      401 and 503 as up)'
                    type: string
                  interval:
                    description: The uptimerobot check interval in seconds
                    minimum: 60
                    type: integer
                  keywordExists:
                    description: Alert if value exist (yes) or doesn't exist (no)
                      (Only if monitor-type is keyword)
                    enum:
                    - "yes"
                    - "no"
                    type: string
                  keywordValue:
                    description: keyword to check on URL (e.g.'search' or '404') (Only
                      if monitor-type is keyword)
                    type: string
                  maintenanceWindows:
                    description: Specify maintenanceWindows i.e. once or recurring
                      “do-not-monitor periods”
                    type: string
                  monitorType:
                    description: The uptimerobot monitor type (http or keyword)
                    enum:
                    - http
                    - keyword
                    type: string
                  statusPages:
                    description: The uptimerobot public status page ID to add this
                      monitor to
                    type: string
                type: object
              url:
                description: URL to monitor
                type: string
              urlFrom:
                description: URL to monitor from either an ingress or route reference
                properties:
                  ingressRef:
                    description: IngressURLSource selects an Ingress to populate the
                      URL with
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  routeRef:
                    description: RouteURLSource selects a Route to populate the URL
                      with
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                type: object
            type: object
          status:
            description: EndpointMonitorStatus defines the observed state of EndpointMonitor
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
